### ISSUE TITLE
能否发一下测试数据和使用流程，工程还没完成能否一块开发完整~

### ISSUE THREAD

**Issue by XiaoXiao2015** [Leavingseason/rnn_recsys#1]
近期打算使用Embedding based News Recommendation，在GitHub找到了你写的开源代码，代码和逻辑都挺清晰的，但整个工程没有完成，是否能够和博主一块把剩余的开发完整呢，我的wx：1204834968

**Comment by Leavingseason** [comment]
大概明天左右会更新一下，修正几个bug和带上一个demo。
